services:
  server:
    build:
      context: .
      dockerfile: PixelUno.Server/Dockerfile    
    restart: always
    container_name: pixeluno_server
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}